---
driver:
  name: docker

driver_config:
  use_sudo: false
  privileged: true
  provision_command: mkdir -p /run/sshd
  run_command: /lib/systemd/systemd

platforms:
  - name: debian-9
    driver_config:
      provision_command:
        - apt-get install udev net-tools -y
  - name: ubuntu-18.04
    driver_config:
      provision_command:
        - apt-get install udev net-tools -y
  - name: centos-7
    driver_config:
      provision_command:
        - yum install udev net-tools -y
  - name: fedora-latest
    driver_config:
      provision_command:
        - yum install udev net-tools -y

provisioner:
  name: salt_solo
  log_level: info
  require_chef: false
  salt_version: latest
  formula: postfix
  salt_copy_filter:
    - .kitchen
    - .git
  pillars:
    top.sls:
      base:
        '*':
          - postfix
    postfix.sls:
      postfix:
         manage_master_config: True
         master_config:
           services:
             relay1:
               wrap: True
               command: smtp
               chroot: false
               type: unix
               extras: '-o smtp_bind_address=127.0.0.1 -o syslog_name=relay1'
               no_args: True
             relay2:
               wrap: True
               command: smtp
               chroot: false
               type: unix
               extras: '-o smtp_bind_address=127.0.0.2 -o syslog_name=relay2'
               no_args: True


verifier:
  name: inspec
  sudo: true
  reporter:
    - cli
  inspec_tests:
    - path: test/integration/default

suites:
  - name: postfix
    provisioner:
      state_top:
        base:
          '*':
            - postfix
            - postfix.config
